---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: gp3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: ebs-nginx
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: ebs-volume
      mountPath: /usr/share/nginx/html
  volumes:
  - name: ebs-volume
    persistentVolumeClaim:
      claimName: ebs-claim
