apiVersion: v1
kind: Pod
metadata:
  name: resources
  namespace: roboshop
  labels:
    environment: prod
    app: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "200m"
        memory: "256Mi"