apiVersion: v1
kind: Pod
metadata:
  name: envar-demo
  namespace: roboshop
spec:
  containers:
  - name: envar-demo-container
    image: nginx
    env:
    - name: ENVIRONMENT
      value: DEV
    - name: demo greeting 
      value: "hello from k8s environment"   


