apiVersion: v1
kind: Pod
metadata:
  name: config-pod
  namespace: roboshop   # added namespace to match your ConfigMap
spec:
  containers:
  - name: config-container
    image: nginx
    env: 
    - name: course
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: course
    - name: duration
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: duration
    - name: mode
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: mode
    - name: trainer
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: trainer
    - name: demo_greeting
      valueFrom:
        configMapKeyRef:
          name: app-config
          key: demo_greeting
