apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-container
    image: nginx 
  env: 
  - name: course
    valuefrom:
      configMapKeyRef:
        name: app-config
        key: course
  - name: duration 
    valuefrom:
      configMapKeyRef:
        name: app-config
        key: duration
  - name: mode 
    valuefrom:
      configMapKeyRef:
        name: app-config
        key: mode
  - name: trainer 
    valuefrom:
      configMapKeyRef:
        name: app-config
        key: trainer
  - name: demo_greeting 
    valuefrom:
      configMapKeyRef:
        name: app-config
        key: demo_greeting                         
