
apiVersion: v1
kind: Pod
metadata:
  name: config-pod-direct
  namespace: roboshop
spec:
  containers:
  - name: config-container-direct
    image: nginx
    envFrom:
    - configMapRef:
        name: app-config
